use_frameworks!

platform :ios, '10.0'

target 'MSDNetworking_Example' do
  pod 'MSDNetworking', :path => '../'

  target 'MSDNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
